// Generated by forgent for agent: staged-reviewer

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/mirandaguillaume/forgent/pkg/dag"
)

func main() {
	var inputFlags multiFlag
	outputDir := flag.String("output", "", "directory to write output files (one per produced type)")
	flag.Var(&inputFlags, "input", "key=value or key=@file.txt (repeatable)")
	flag.Parse()

	var provider llmProvider
	if key := os.Getenv("OPENROUTER_API_KEY"); key != "" {
		model := os.Getenv("OPENROUTER_MODEL")
		if model == "" {
			model = "anthropic/claude-3.5-haiku"
		}
		provider = newOpenRouterProvider(key, model)
	} else if key := os.Getenv("ANTHROPIC_API_KEY"); key != "" {
		provider = newAnthropicProvider(key)
	} else {
		fmt.Fprintln(os.Stderr, "OPENROUTER_API_KEY or ANTHROPIC_API_KEY is required")
		os.Exit(1)
	}

	nodes := []*dag.Node{
		{
			ID:         "pr-triage",
			Consumes:   []string{"pr_url"},
			Produces:   []string{"triage_report"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: pr-triage

## Approach
gate-check

## Steps
1. fetch PR metadata and diff via gh
2. check if PR is closed, draft, automated, or already reviewed
3. if eligible, summarize the nature of changes (files changed, purpose, risk areas)
4. return eligibility status with reason and structured summary

## Guardrails
- timeout: 2min
- fail_closed
- max_summary_length: 500

## Input
pr_url:
{{ .pr_url }}

## Output
Produce: triage_report
`, []string{"triage_report"}),
		},
		{
			ID:         "bug-scanner",
			Consumes:   []string{"git_diff", "source_code", "code_analysis"},
			Produces:   []string{"review_issues__bug_scanner"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: bug-scanner

## Approach
diff-first

## Steps
1. parse each changed hunk — note file, line numbers, language
2. for every removed or added line, apply the forensic checklist below
3. if source_code is non-empty, look up the full function body around each hunk for context
4. emit one issue per finding with file, line, severity, and exact quote from the diff

## Guardrails
- timeout: 5min
- no_nitpicks
- no_style_issues
- skip_if_source_empty: if source_code is empty, analyse the diff alone without fabricating context

## Input
git_diff:
{{ .git_diff }}

source_code:
{{ .source_code }}

code_analysis:
{{ .code_analysis }}

## Output
Produce: review_issues
`, []string{"review_issues__bug_scanner"}),
		},
		{
			ID:         "git-history-reviewer",
			Consumes:   []string{"pr_diff", "git_blame"},
			Produces:   []string{"review_issues__git_history_reviewer"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: git-history-reviewer

## Approach
history-first

## Steps
1. read git blame for modified files
2. analyze commit history of modified code sections
3. identify bugs in light of historical context
4. flag regressions or patterns that previously caused issues

## Guardrails
- timeout: 5min
- max_history_depth: 20

## Input
pr_diff:
{{ .pr_diff }}

git_blame:
{{ .git_blame }}

## Output
Produce: review_issues
`, []string{"review_issues__git_history_reviewer"}),
		},
		{
			ID:         "merge__review_issues",
			Consumes:   []string{"review_issues__bug_scanner", "review_issues__git_history_reviewer"},
			Produces:   []string{"review_issues"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: func(ctx context.Context, inputs map[string]any) (map[string]any, error) {
				var parts []string
				if v, ok := inputs["review_issues__bug_scanner"]; ok {
					parts = append(parts, fmt.Sprintf("=== review_issues__bug_scanner ===\n%v", v))
				}
				if v, ok := inputs["review_issues__git_history_reviewer"]; ok {
					parts = append(parts, fmt.Sprintf("=== review_issues__git_history_reviewer ===\n%v", v))
				}
				return map[string]any{"review_issues": strings.Join(parts, "\n\n")}, nil
			},
		},
		{
			ID:         "pr-commenter",
			Consumes:   []string{"scored_issues", "pr_url"},
			Produces:   []string{"review_comment"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: pr-commenter

## Approach
output-format

## Steps
1. re-verify PR eligibility to confirm not closed or merged since analysis
2. format issues with file links using full SHA
3. post comment via gh pr comment
4. if no issues, post no issues found message

## Guardrails
- timeout: 2min
- require_full_sha
- max_issues: 20

## Input
scored_issues:
{{ .scored_issues }}

pr_url:
{{ .pr_url }}

## Output
Produce: review_comment
`, []string{"review_comment"}),
		},
	}

	d, err := dag.New(nodes...)
	if err != nil {
		fmt.Fprintf(os.Stderr, "DAG error: %v\n", err)
		os.Exit(1)
	}

	inputs := discoverInputs([]string{"pr_url", "git_diff", "source_code", "code_analysis", "pr_diff", "git_blame", "scored_issues"})
	for _, kv := range inputFlags {
		k, v := parseInputFlag(kv)
		if k != "" {
			inputs[k] = v
		}
	}

	results, err := d.Execute(context.Background(), dag.WithInputs(inputs))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Execution error: %v\n", err)
		os.Exit(1)
	}

	for k, v := range results {
		content := fmt.Sprintf("%v", v)
		if *outputDir != "" {
			if err := os.MkdirAll(*outputDir, 0755); err != nil {
				fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", *outputDir, err)
				continue
			}
			path := filepath.Join(*outputDir, k+".md")
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
			} else {
				fmt.Printf("wrote %s\n", path)
			}
		} else {
			fmt.Printf("=== %s ===\n%s\n\n", k, content)
		}
	}
}

// llmProvider abstracts an LLM backend for text completion.
type llmProvider interface {
	Complete(ctx context.Context, prompt string) (string, error)
}

// anthropicProvider calls the Anthropic Messages API.
type anthropicProvider struct {
	apiKey string
}

func newAnthropicProvider(apiKey string) *anthropicProvider {
	return &anthropicProvider{apiKey: apiKey}
}

type anthropicRequest struct {
	Model     string             `json:"model"`
	MaxTokens int                `json:"max_tokens"`
	Messages  []anthropicMessage `json:"messages"`
}

type anthropicMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type anthropicResponse struct {
	Content []anthropicContent `json:"content"`
	Error   *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

type anthropicContent struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

// openRouterProvider calls the OpenRouter API (OpenAI-compatible).
type openRouterProvider struct {
	apiKey string
	model  string
}

func newOpenRouterProvider(apiKey, model string) *openRouterProvider {
	return &openRouterProvider{apiKey: apiKey, model: model}
}

type openRouterRequest struct {
	Model    string             `json:"model"`
	Messages []anthropicMessage `json:"messages"`
}

type openRouterResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *openRouterProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := openRouterRequest{
		Model:    p.model,
		Messages: []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://openrouter.ai/api/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result openRouterResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Choices) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Choices[0].Message.Content, nil
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *anthropicProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := anthropicRequest{
		Model:     "claude-sonnet-4-20250514",
		MaxTokens: 8192,
		Messages:  []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://api.anthropic.com/v1/messages", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", p.apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result anthropicResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Content) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Content[0].Text, nil
}

func makeSkillRunner(
	provider llmProvider,
	promptTemplate string,
	produces []string,
) func(context.Context, map[string]any) (map[string]any, error) {
	return func(ctx context.Context, inputs map[string]any) (map[string]any, error) {
		prompt := promptTemplate
		for k, v := range inputs {
			prompt = strings.ReplaceAll(prompt, "{{ ."+k+" }}", fmt.Sprintf("%v", v))
		}
		response, err := provider.Complete(ctx, prompt)
		if err != nil {
			return nil, err
		}
		out := make(map[string]any, len(produces))
		for _, p := range produces {
			out[p] = response
		}
		return out, nil
	}
}

// multiFlag allows --input to be specified multiple times.
type multiFlag []string

func (f *multiFlag) String() string { return strings.Join(*f, ", ") }
func (f *multiFlag) Set(v string) error {
	*f = append(*f, v)
	return nil
}

// parseInputFlag parses "key=value" or "key=@file.txt" into (key, content).
func parseInputFlag(kv string) (string, string) {
	idx := strings.IndexByte(kv, '=')
	if idx < 0 {
		return "", ""
	}
	k, v := kv[:idx], kv[idx+1:]
	if strings.HasPrefix(v, "@") {
		data, err := os.ReadFile(v[1:])
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: cannot read input file %s: %v\n", v[1:], err)
			return k, ""
		}
		return k, string(data)
	}
	return k, v
}

func discoverInputs(needed []string) map[string]any {
	inputs := make(map[string]any)
	for _, key := range needed {
		switch key {
		case "git_diff":
			if out, err := exec.Command("git", "diff", "HEAD").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "file_tree":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "source_code":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				files := strings.Split(strings.TrimSpace(string(out)), "\n")
				var sb strings.Builder
				for _, f := range files {
					if content, err := os.ReadFile(f); err == nil {
						fmt.Fprintf(&sb, "=== %s ===\n%s\n", f, string(content))
						if sb.Len() > 100000 {
							break
						}
					}
				}
				inputs[key] = sb.String()
			}
		case "pr_diff":
			if out, err := exec.Command("gh", "pr", "diff").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "pr_url":
			if out, err := exec.Command("gh", "pr", "view", "--json", "url", "-q", ".url").Output(); err == nil {
				inputs[key] = strings.TrimSpace(string(out))
			}
		case "code_analysis":
			// code_analysis is computed externally (by CLI or bench) and passed via --input.
			// If not provided but git_diff is available, leave empty — the caller should provide it.
		}
	}
	return inputs
}
