package forgent

import (
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/mirandaguillaume/forgent/pkg/model"
)

// GenerateAgentGo generates a complete Go main.go program for an agent's DAG runtime.
func GenerateAgentGo(agent model.AgentComposition, skills []model.SkillBehavior) string {
	var b strings.Builder

	// Collect all consumed types across skills that have no internal producer
	allProduced := map[string]bool{}
	for _, s := range skills {
		for _, p := range s.Context.Produces {
			allProduced[p] = true
		}
	}
	externalInputs := []string{}
	seen := map[string]bool{}
	for _, s := range skills {
		for _, c := range s.Context.Consumes {
			if !allProduced[c] && !seen[c] {
				externalInputs = append(externalInputs, c)
				seen[c] = true
			}
		}
	}

	// Agent header comment + package declaration
	fmt.Fprintf(&b, "// Generated by forgent for agent: %s\n\n", agent.Agent)
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"bytes\"\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"os\"\n")
	b.WriteString("\t\"os/exec\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString("\t\"time\"\n\n")
	b.WriteString("\t\"github.com/mirandaguillaume/forgent/pkg/dag\"\n")
	b.WriteString(")\n\n")

	// main function
	b.WriteString("func main() {\n")
	b.WriteString("\tvar provider llmProvider\n")
	b.WriteString("\tif key := os.Getenv(\"OPENROUTER_API_KEY\"); key != \"\" {\n")
	b.WriteString("\t\tmodel := os.Getenv(\"OPENROUTER_MODEL\")\n")
	b.WriteString("\t\tif model == \"\" {\n")
	b.WriteString("\t\t\tmodel = \"anthropic/claude-haiku-4-5-20251001\"\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tprovider = newOpenRouterProvider(key, model)\n")
	b.WriteString("\t} else if key := os.Getenv(\"ANTHROPIC_API_KEY\"); key != \"\" {\n")
	b.WriteString("\t\tprovider = newAnthropicProvider(key)\n")
	b.WriteString("\t} else {\n")
	b.WriteString("\t\tfmt.Fprintln(os.Stderr, \"OPENROUTER_API_KEY or ANTHROPIC_API_KEY is required\")\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	// Nodes
	b.WriteString("\tnodes := []*dag.Node{\n")
	for _, s := range skills {
		prompt := BuildPromptTemplate(s)
		escapedPrompt := strings.ReplaceAll(prompt, "`", "` + \"`\" + `")

		b.WriteString("\t\t{\n")
		fmt.Fprintf(&b, "\t\t\tID: %q,\n", s.Skill)

		// Consumes
		if len(s.Context.Consumes) > 0 {
			consumeStrs := make([]string, len(s.Context.Consumes))
			for i, c := range s.Context.Consumes {
				consumeStrs[i] = fmt.Sprintf("%q", c)
			}
			fmt.Fprintf(&b, "\t\t\tConsumes: []string{%s},\n", strings.Join(consumeStrs, ", "))
		}

		// Produces
		if len(s.Context.Produces) > 0 {
			produceStrs := make([]string, len(s.Context.Produces))
			for i, p := range s.Context.Produces {
				produceStrs[i] = fmt.Sprintf("%q", p)
			}
			fmt.Fprintf(&b, "\t\t\tProduces: []string{%s},\n", strings.Join(produceStrs, ", "))
		}

		// Retry / timeout (defaults: 0)
		fmt.Fprintf(&b, "\t\t\tMaxRetries: %d,\n", 0)
		fmt.Fprintf(&b, "\t\t\tTimeout:    time.Duration(%d),\n", 0)

		// Run function
		fmt.Fprintf(&b, "\t\t\tRun: makeSkillRunner(provider, `%s`, []string{", escapedPrompt)
		for i, p := range s.Context.Produces {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", p)
		}
		b.WriteString("}),\n")
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}\n\n")

	// Build and execute DAG
	b.WriteString("\td, err := dag.New(nodes...)\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"DAG error: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")

	// Discover inputs
	fmt.Fprintf(&b, "\tinputs := discoverInputs([]string{%s})\n\n",
		joinQuoted(externalInputs))

	b.WriteString("\tresults, err := d.Execute(context.Background(), dag.WithInputs(inputs))\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tfmt.Fprintf(os.Stderr, \"Execution error: %v\\n\", err)\n")
	b.WriteString("\t\tos.Exit(1)\n")
	b.WriteString("\t}\n\n")
	b.WriteString("\tfor k, v := range results {\n")
	b.WriteString("\t\tfmt.Printf(\"=== %s ===\\n%v\\n\\n\", k, v)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// makeSkillRunner helper
	b.WriteString(makeSkillRunnerCode())

	// discoverInputs helper
	b.WriteString(discoverInputsCode())

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: generated code failed gofmt: %v\n", err)
		return b.String()
	}
	return string(formatted)
}

// GenerateGoMod generates a go.mod file for the generated runtime.
func GenerateGoMod(agentName string) string {
	safeName := strings.ToLower(strings.ReplaceAll(agentName, " ", "-"))
	var b strings.Builder
	fmt.Fprintf(&b, "module %s\n\n", safeName)
	b.WriteString("go 1.22\n\n")
	b.WriteString("require github.com/mirandaguillaume/forgent v0.0.0\n\n")
	b.WriteString("replace github.com/mirandaguillaume/forgent => ../..\n")
	return b.String()
}

func joinQuoted(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(quoted, ", ")
}

func makeSkillRunnerCode() string {
	return `// llmProvider abstracts an LLM backend for text completion.
type llmProvider interface {
	Complete(ctx context.Context, prompt string) (string, error)
}

// anthropicProvider calls the Anthropic Messages API.
type anthropicProvider struct {
	apiKey string
}

func newAnthropicProvider(apiKey string) *anthropicProvider {
	return &anthropicProvider{apiKey: apiKey}
}

type anthropicRequest struct {
	Model     string             ` + "`" + `json:"model"` + "`" + `
	MaxTokens int                ` + "`" + `json:"max_tokens"` + "`" + `
	Messages  []anthropicMessage ` + "`" + `json:"messages"` + "`" + `
}

type anthropicMessage struct {
	Role    string ` + "`" + `json:"role"` + "`" + `
	Content string ` + "`" + `json:"content"` + "`" + `
}

type anthropicResponse struct {
	Content []anthropicContent ` + "`" + `json:"content"` + "`" + `
	Error   *struct {
		Message string ` + "`" + `json:"message"` + "`" + `
	} ` + "`" + `json:"error,omitempty"` + "`" + `
}

type anthropicContent struct {
	Type string ` + "`" + `json:"type"` + "`" + `
	Text string ` + "`" + `json:"text"` + "`" + `
}

// openRouterProvider calls the OpenRouter API (OpenAI-compatible).
type openRouterProvider struct {
	apiKey string
	model  string
}

func newOpenRouterProvider(apiKey, model string) *openRouterProvider {
	return &openRouterProvider{apiKey: apiKey, model: model}
}

type openRouterRequest struct {
	Model    string              ` + "`" + `json:"model"` + "`" + `
	Messages []anthropicMessage  ` + "`" + `json:"messages"` + "`" + `
}

type openRouterResponse struct {
	Choices []struct {
		Message struct {
			Content string ` + "`" + `json:"content"` + "`" + `
		} ` + "`" + `json:"message"` + "`" + `
	} ` + "`" + `json:"choices"` + "`" + `
	Error *struct {
		Message string ` + "`" + `json:"message"` + "`" + `
	} ` + "`" + `json:"error,omitempty"` + "`" + `
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *openRouterProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := openRouterRequest{
		Model:    p.model,
		Messages: []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://openrouter.ai/api/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result openRouterResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Choices) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Choices[0].Message.Content, nil
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *anthropicProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := anthropicRequest{
		Model:     "claude-sonnet-4-20250514",
		MaxTokens: 8192,
		Messages:  []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://api.anthropic.com/v1/messages", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", p.apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result anthropicResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Content) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Content[0].Text, nil
}

func makeSkillRunner(
	provider llmProvider,
	promptTemplate string,
	produces []string,
) func(context.Context, map[string]any) (map[string]any, error) {
	return func(ctx context.Context, inputs map[string]any) (map[string]any, error) {
		prompt := promptTemplate
		for k, v := range inputs {
			prompt = strings.ReplaceAll(prompt, "{{ ."+k+" }}", fmt.Sprintf("%v", v))
		}
		response, err := provider.Complete(ctx, prompt)
		if err != nil {
			return nil, err
		}
		out := make(map[string]any, len(produces))
		for _, p := range produces {
			out[p] = response
		}
		return out, nil
	}
}

`
}

func discoverInputsCode() string {
	return `func discoverInputs(needed []string) map[string]any {
	inputs := make(map[string]any)
	for _, key := range needed {
		switch key {
		case "git_diff":
			if out, err := exec.Command("git", "diff", "HEAD").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "file_tree":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "source_code":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				files := strings.Split(strings.TrimSpace(string(out)), "\n")
				var sb strings.Builder
				for _, f := range files {
					if content, err := os.ReadFile(f); err == nil {
						fmt.Fprintf(&sb, "=== %s ===\n%s\n", f, string(content))
						if sb.Len() > 100000 {
							break
						}
					}
				}
				inputs[key] = sb.String()
			}
		case "pr_diff":
			if out, err := exec.Command("gh", "pr", "diff").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "pr_url":
			if out, err := exec.Command("gh", "pr", "view", "--json", "url", "-q", ".url").Output(); err == nil {
				inputs[key] = strings.TrimSpace(string(out))
			}
		}
	}
	return inputs
}
`
}
