// Generated by forgent for agent: ci-reviewer

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/mirandaguillaume/forgent/pkg/dag"
)

func main() {
	var inputFlags multiFlag
	outputDir := flag.String("output", "", "directory to write output files (one per produced type)")
	flag.Var(&inputFlags, "input", "key=value or key=@file.txt (repeatable)")
	flag.Parse()

	var provider llmProvider
	if key := os.Getenv("OPENROUTER_API_KEY"); key != "" {
		model := os.Getenv("OPENROUTER_MODEL")
		if model == "" {
			model = "anthropic/claude-3.5-haiku"
		}
		provider = newOpenRouterProvider(key, model)
	} else if key := os.Getenv("ANTHROPIC_API_KEY"); key != "" {
		provider = newAnthropicProvider(key)
	} else {
		fmt.Fprintln(os.Stderr, "OPENROUTER_API_KEY or ANTHROPIC_API_KEY is required")
		os.Exit(1)
	}

	nodes := []*dag.Node{
		{
			ID:         "bug-scanner",
			Consumes:   []string{"git_diff", "source_code", "code_analysis"},
			Produces:   []string{"review_issues"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: bug-scanner

## Approach
diff-first

## Steps
1. parse each changed hunk — note file, line numbers, language
2. for every removed or added line, apply the forensic checklist below
3. if source_code is non-empty, look up the full function body around each hunk for context
4. emit one issue per finding with file, line, severity, and exact quote from the diff

## Guardrails
- timeout: 5min
- no_nitpicks
- no_style_issues
- skip_if_source_empty: if source_code is empty, analyse the diff alone without fabricating context

## Input
git_diff:
{{ .git_diff }}

source_code:
{{ .source_code }}

code_analysis:
{{ .code_analysis }}

## Output
Produce: review_issues
`, []string{"review_issues"}),
		},
		{
			ID:         "ts-linter",
			Consumes:   []string{"file_tree", "source_code"},
			Produces:   []string{"lint_results"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: ts-linter

## Approach
static-analysis

## Steps
1. check for common anti-patterns
2. produce structured lint report

## Guardrails
- timeout: 5min
- max_file_size: 500KB

## Input
file_tree:
{{ .file_tree }}

source_code:
{{ .source_code }}

## Output
Produce: lint_results
`, []string{"lint_results"}),
		},
		{
			ID:         "type-checker",
			Consumes:   []string{"file_tree", "source_code"},
			Produces:   []string{"type_errors"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: type-checker

## Approach
static-analysis

## Steps
1. run TypeScript compiler in noEmit mode
2. collect type errors with file locations

## Guardrails
- timeout: 5min
- max_file_size: 500KB

## Input
file_tree:
{{ .file_tree }}

source_code:
{{ .source_code }}

## Output
Produce: type_errors
`, []string{"type_errors"}),
		},
		{
			ID:         "review-commenter",
			Consumes:   []string{"git_diff", "review_issues", "lint_results", "type_errors", "source_code"},
			Produces:   []string{"review_comments"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: review-commenter

## Approach
diff-first

## Steps
1. read review_issues — these are confirmed bugs from static analysis; include every one verbatim
2. read lint_results and type_errors if non-empty — add any issues not already in review_issues
3. re-read the git diff — look for issues missed by upstream skills using the same forensic checklist
4. for each issue: write a comment with file path, line number, exact code quote, explanation of why it is wrong, and a concrete fix
5. do not write generic advice — every comment must reference a specific line in the diff
6. do not praise the code or summarise the PR — output review comments only

## Guardrails
- max_comments: 20
- timeout: 5min
- no_approve_without_tests
- no_generic_advice: every comment must cite file:line and quote the offending code
- no_summary: do not summarise what the PR does — only flag problems

## Input
git_diff:
{{ .git_diff }}

review_issues:
{{ .review_issues }}

lint_results:
{{ .lint_results }}

type_errors:
{{ .type_errors }}

source_code:
{{ .source_code }}

## Output
Produce: review_comments
`, []string{"review_comments"}),
		},
		{
			ID:         "risk-scorer",
			Consumes:   []string{"git_diff", "test_results", "lint_results"},
			Produces:   []string{"risk_score"},
			MaxRetries: 0,
			Timeout:    time.Duration(0),
			Run: makeSkillRunner(provider, `You are: risk-scorer

## Approach
diff-first

## Steps
1. analyze git diff scope and complexity
2. cross-reference with test coverage
3. cross-reference with lint severity
4. assign risk score (0-10)

## Guardrails
- timeout: 3min
- require_risk_score

## Input
git_diff:
{{ .git_diff }}

test_results:
{{ .test_results }}

lint_results:
{{ .lint_results }}

## Output
Produce: risk_score
`, []string{"risk_score"}),
		},
	}

	d, err := dag.New(nodes...)
	if err != nil {
		fmt.Fprintf(os.Stderr, "DAG error: %v\n", err)
		os.Exit(1)
	}

	inputs := discoverInputs([]string{"git_diff", "source_code", "code_analysis", "file_tree", "test_results"})
	for _, kv := range inputFlags {
		k, v := parseInputFlag(kv)
		if k != "" {
			inputs[k] = v
		}
	}

	results, err := d.Execute(context.Background(), dag.WithInputs(inputs))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Execution error: %v\n", err)
		os.Exit(1)
	}

	for k, v := range results {
		content := fmt.Sprintf("%v", v)
		if *outputDir != "" {
			if err := os.MkdirAll(*outputDir, 0755); err != nil {
				fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", *outputDir, err)
				continue
			}
			path := filepath.Join(*outputDir, k+".md")
			if err := os.WriteFile(path, []byte(content), 0644); err != nil {
				fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
			} else {
				fmt.Printf("wrote %s\n", path)
			}
		} else {
			fmt.Printf("=== %s ===\n%s\n\n", k, content)
		}
	}
}

// llmProvider abstracts an LLM backend for text completion.
type llmProvider interface {
	Complete(ctx context.Context, prompt string) (string, error)
}

// anthropicProvider calls the Anthropic Messages API.
type anthropicProvider struct {
	apiKey string
}

func newAnthropicProvider(apiKey string) *anthropicProvider {
	return &anthropicProvider{apiKey: apiKey}
}

type anthropicRequest struct {
	Model     string             `json:"model"`
	MaxTokens int                `json:"max_tokens"`
	Messages  []anthropicMessage `json:"messages"`
}

type anthropicMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type anthropicResponse struct {
	Content []anthropicContent `json:"content"`
	Error   *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

type anthropicContent struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

// openRouterProvider calls the OpenRouter API (OpenAI-compatible).
type openRouterProvider struct {
	apiKey string
	model  string
}

func newOpenRouterProvider(apiKey, model string) *openRouterProvider {
	return &openRouterProvider{apiKey: apiKey, model: model}
}

type openRouterRequest struct {
	Model    string             `json:"model"`
	Messages []anthropicMessage `json:"messages"`
}

type openRouterResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
	Error *struct {
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *openRouterProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := openRouterRequest{
		Model:    p.model,
		Messages: []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://openrouter.ai/api/v1/chat/completions", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.apiKey)
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result openRouterResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Choices) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Choices[0].Message.Content, nil
}

// NOTE: ctx is forwarded to the HTTP request for cancellation support
func (p *anthropicProvider) Complete(ctx context.Context, prompt string) (string, error) {
	reqBody := anthropicRequest{
		Model:     "claude-sonnet-4-20250514",
		MaxTokens: 8192,
		Messages:  []anthropicMessage{{Role: "user", Content: prompt}},
	}
	body, err := json.Marshal(reqBody)
	if err != nil {
		return "", fmt.Errorf("marshal request: %w", err)
	}
	req, err := http.NewRequestWithContext(ctx, "POST", "https://api.anthropic.com/v1/messages", bytes.NewReader(body))
	if err != nil {
		return "", fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", p.apiKey)
	req.Header.Set("anthropic-version", "2023-06-01")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("API error %d: %s", resp.StatusCode, string(respBody))
	}
	var result anthropicResponse
	if err := json.Unmarshal(respBody, &result); err != nil {
		return "", fmt.Errorf("unmarshal response: %w", err)
	}
	if result.Error != nil {
		return "", fmt.Errorf("API error: %s", result.Error.Message)
	}
	if len(result.Content) == 0 {
		return "", fmt.Errorf("empty response from API")
	}
	return result.Content[0].Text, nil
}

func makeSkillRunner(
	provider llmProvider,
	promptTemplate string,
	produces []string,
) func(context.Context, map[string]any) (map[string]any, error) {
	return func(ctx context.Context, inputs map[string]any) (map[string]any, error) {
		prompt := promptTemplate
		for k, v := range inputs {
			prompt = strings.ReplaceAll(prompt, "{{ ."+k+" }}", fmt.Sprintf("%v", v))
		}
		response, err := provider.Complete(ctx, prompt)
		if err != nil {
			return nil, err
		}
		out := make(map[string]any, len(produces))
		for _, p := range produces {
			out[p] = response
		}
		return out, nil
	}
}

// multiFlag allows --input to be specified multiple times.
type multiFlag []string

func (f *multiFlag) String() string { return strings.Join(*f, ", ") }
func (f *multiFlag) Set(v string) error {
	*f = append(*f, v)
	return nil
}

// parseInputFlag parses "key=value" or "key=@file.txt" into (key, content).
func parseInputFlag(kv string) (string, string) {
	idx := strings.IndexByte(kv, '=')
	if idx < 0 {
		return "", ""
	}
	k, v := kv[:idx], kv[idx+1:]
	if strings.HasPrefix(v, "@") {
		data, err := os.ReadFile(v[1:])
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: cannot read input file %s: %v\n", v[1:], err)
			return k, ""
		}
		return k, string(data)
	}
	return k, v
}

func discoverInputs(needed []string) map[string]any {
	inputs := make(map[string]any)
	for _, key := range needed {
		switch key {
		case "git_diff":
			if out, err := exec.Command("git", "diff", "HEAD").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "file_tree":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "source_code":
			if out, err := exec.Command("git", "ls-files").Output(); err == nil {
				files := strings.Split(strings.TrimSpace(string(out)), "\n")
				var sb strings.Builder
				for _, f := range files {
					if content, err := os.ReadFile(f); err == nil {
						fmt.Fprintf(&sb, "=== %s ===\n%s\n", f, string(content))
						if sb.Len() > 100000 {
							break
						}
					}
				}
				inputs[key] = sb.String()
			}
		case "pr_diff":
			if out, err := exec.Command("gh", "pr", "diff").Output(); err == nil {
				inputs[key] = string(out)
			}
		case "pr_url":
			if out, err := exec.Command("gh", "pr", "view", "--json", "url", "-q", ".url").Output(); err == nil {
				inputs[key] = strings.TrimSpace(string(out))
			}
		case "code_analysis":
			// code_analysis is computed externally (by CLI or bench) and passed via --input.
			// If not provided but git_diff is available, leave empty — the caller should provide it.
		}
	}
	return inputs
}
